Update tekstovniVmesnik.ml
matijapretnar/programiranje-1 pull request #34
Opened 2024-02-19 19:07 UTC by lukaponikvar

Avtomat se po branju niza ne vrne v začetno stanje in torej nepravilno sprejema nize, ki sledijo.

2024-02-21 14:56 UTC, matijapretnar commented
Pa res! Razmišljam, če bi bilo bolje, da bi bilo vračanje v začetno stanje posebno dejanje uporabniškega vmesnika, torej da branje niza deluje kot sedaj, ampak ima na vsaki točki uporabnik možnost, da stanje spravi nazaj v začetno. Kaj menite?

2024-02-21 15:24 UTC, lukaponikvar commented
Zagotovo bi se to moralo zgoditi, če vnesemo neveljavem niz. Drugače pa je možnost dopolnitve začetnega niza verjetno dobrodošla. Na primer:
1) Izpiši avtomat
2) Dopolni niz
3) Preberi nov niz
ali pa kaj podobnega?

2024-02-26 08:27 UTC, matijapretnar commented
Jaz bi predlagal:

```
2. beri znake
3. nastavi na začetno stanje
```

In če smo v stanju `s` ter poskusimo prebrati niz, ki bi nas pripeljal v neveljavno stanje, javimo napako in povrnemo nazaj na stanje `s` (in ne v začetno stanje), torej kot če niza ne bi vnesli.

Če se vam to zdi smiselno, lahko naredite PR 👕

2024-02-27 07:32 UTC, matijapretnar commented
To bi bilo treba narediti tako, da se `VrniVPrvotnoStanje` doda med `msg`, ne pod `stanje_vmesnika`. Potem pa v `update` ne samo nastavimo avtomat na začetno stanje, ampak tudi vmesnik nastavimo na `SeznamMoznosti`.

2024-02-29 12:08 UTC, matijapretnar requested changes

2024-02-29 12:08 UTC, matijapretnar commented on projekt/src/tekstovniVmesnik/tekstovniVmesnik.ml
> +      ZamenjajVmesnik SeznamMoznosti;
Ta podpičja so odveč. Pa tudi prazna vrstica spodaj je izginila. Mogoče Ali lahko vse skupaj pošljete še čez `ocamlformat` (oz. `dune fmt`), da se ne spremeni stil?

2024-02-29 12:08 UTC, matijapretnar commented on projekt/src/tekstovniVmesnik/tekstovniVmesnik.ml
> +  | VrniVPrvotnoStanje -> { model with stanje_avtomata = zacetno_stanje model.avtomat}
V kakšnem stanju je vmesnik? Verjetno je trenutno edina možnost, da je bil pred tem v `SeznamMoznosti`, ampak je bolje, če to nastavimo eksplicitno.

2024-03-01 13:06 UTC, merged